version: "3.7"
services:
  nginx:
    build:
      context: ./front/deploy/.nginx/
    ports:
      - "80:80"
    restart: always
    networks:
      - skarr_pro
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=RY045912LO
      - MONGO_INITDB_DATABASE=skarr_pro
    volumes:
      - ./skarr_pro_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongodb    
    command: [--auth]
    restart: on-failure
    networks:
      - skarr_pro
  backend:
    depends_on:
      - nginx
      - mongodb
    build:
      context: ./back/
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - skarr_pro
  frontend:
    depends_on:
      - nginx
      - backend
    build:
      context: ./front/
    ports:
      - "3001:3001"
    command: start
    container_name: frontend
    networks:
      - skarr_pro
networks:
  skarr_pro:
    driver: bridge
volumes:
  skar_pro_db:
