version: "3.4"
services:
  nginx:
    build:
      context: ./front/deploy/.nginx/
    ports:
      - "80:80"
    restart: always
    networks:
      - veza
  postgres:
    image: postgres:latest
    depends_on:
      - nginx
    environment:
      POSTGRES_DB: "veza"
      POSTGRES_USER: "veza_admin"
      POSTGRES_PASSWORD: "R2a}z*UzqEML"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - veza
  backend:
    depends_on:
      - nginx
      - postgres
    image: ${DOCKER_REGISTRY-}vezabackend
    build:
      context: ./back/Veza.WebSite/
      dockerfile: Dockerfile
    networks:
      - veza
  frontend:
    depends_on:
      - nginx
      - backend
    build:
      context: ./front/
    ports:
      - "3001:3001"
    command: start
    networks:
      - veza
  docsify:
    build:
      context: ./docsify/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - veza
networks:
  veza:
    driver: bridge
